// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(props) {
  var match = React.useState(function () {
        return 1;
      });
  var setA = match[1];
  React.useEffect(function () {
        setA(function (a) {
              return a;
            });
      });
  return String(match[0]);
}

var make = Home;

export {
  make ,
}
/* react Not a pure module */
